services:
  spark-master:
    image: ghcr.io/auduvignac/flight:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - ROLE=MASTER
      - SPARK_LOCAL_DIRS=/opt/spark/local      # +++ dit à Spark où shuffler
    volumes:
      - ./data:/app/data
      - ./delta:/app/delta
      - ./spark-local:/opt/spark/local         # +++ disque shuffle local
    ports:
      - "8080:8080"  # Spark UI (master)
      - "7077:7077"  # Spark master service port
    restart: unless-stopped

  spark-worker:
    image: ghcr.io/auduvignac/flight:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - ROLE=WORKER
      - SPARK_LOCAL_DIRS=/opt/spark/local      # +++
      - SPARK_WORKER_CORES=2                   # +++ ressources du worker
      - SPARK_WORKER_MEMORY=4g                 # +++ mémoire du worker
    volumes:
      - ./data:/app/data
      - ./delta:/app/delta
      - ./spark-local:/opt/spark/local         # +++
    depends_on:
      - spark-master
    restart: unless-stopped

  spark-submit:
    image: ghcr.io/auduvignac/flight:latest
    container_name: spark-submit
    environment:
      - SPARK_MODE=submit
      - SPARK_MASTER_URL=spark://spark-master:7077
      - ROLE=SUBMIT
      - SPARK_LOCAL_DIRS=/opt/spark/local      # +++
    volumes:
      - ./data:/app/data
      - ./delta:/app/delta
      - ./spark-local:/opt/spark/local         # +++
    working_dir: /app
    depends_on:
      - spark-master
    command: ["tail", "-f", "/dev/null"]
    restart: unless-stopped