services:
  spark-master:
    image: ghcr.io/auduvignac/flight:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - ROLE=MASTER
    volumes:
      - ./data:/app/data
      - ./delta:/app/delta
    ports:
      - "8080:8080"  # Spark UI (master)
      - "7077:7077"  # Spark master service port
    restart: unless-stopped

  spark-worker:
    image: ghcr.io/auduvignac/flight:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - ROLE=WORKER
    volumes:
      - ./data:/app/data
      - ./delta:/app/delta
    depends_on:
      - spark-master
    restart: unless-stopped

  spark-submit:
    image: ghcr.io/auduvignac/flight:latest
    container_name: spark-submit
    environment:
      - SPARK_MODE=submit
      - SPARK_MASTER_URL=spark://spark-master:7077
      - ROLE=SUBMIT
    volumes:
      - ./data:/app/data
      - ./delta:/app/delta
    working_dir: /app
    depends_on:
      - spark-master
    command: ["tail", "-f", "/dev/null"]
    restart: unless-stopped