volumes:
  spark-delta:
  spark-local:

x-env-common: &common-env
  LOG_CONFIG_PATH: /opt/spark/conf/log4j2.properties
  APPLICATION_CONFIG_PATH: /opt/config/application.conf
  SPARK_MASTER_URL: spark://spark-master:7077
  SPARK_LOCAL_DIRS: /opt/spark/local
  SPARK_CONF: /opt/spark/conf/spark.conf

services:

  spark-master:
    image: ghcr.io/auduvignac/flight:latest
    container_name: spark-master
    environment:
      <<: *common-env
      SPARK_MODE: master
      SPARK_MASTER_HOST: spark-master
      ROLE: MASTER
    volumes:
      - ./data:/app/data                  # dataset local rapide
      - spark-delta:/app/delta            # delta FROID & rapide
      - spark-local:/opt/spark/local      # shuffle ultra rapide
      - ./conf/spark.conf:/opt/spark/conf/spark.conf:ro
      - ./conf/application.conf:/opt/config/application.conf:ro
      - ./conf/log4j2-submit.properties:/opt/spark/conf/log4j2.properties:ro
    ports:
      - "8080:8080"
      - "7077:7077"
    restart: unless-stopped

  spark-worker:
    image: ghcr.io/auduvignac/flight:latest
    container_name: spark-worker
    environment:
      <<: *common-env
      SPARK_MODE: worker
      ROLE: WORKER
    volumes:
      - ./data:/app/data
      - spark-delta:/app/delta
      - spark-local:/opt/spark/local
      - ./conf/spark.conf:/opt/spark/conf/spark.conf:ro
    depends_on:
      - spark-master
    restart: unless-stopped

  spark-submit:
    image: ghcr.io/auduvignac/flight:latest
    container_name: spark-submit
    environment:
      <<: *common-env
      SPARK_MODE: submit
      ROLE: SUBMIT
    volumes:
      - ./data:/app/data
      - spark-delta:/app/delta
      - spark-local:/opt/spark/local
      - ./conf/spark.conf:/opt/spark/conf/spark.conf:ro
      - ./conf/application.conf:/opt/config/application.conf:ro
      - ./conf/log4j2-submit.properties:/opt/spark/conf/log4j2.properties:ro
      - ./spark-submit.sh:/app/spark-submit.sh:ro
    working_dir: /app
    depends_on:
      - spark-master
    command: ["tail", "-f", "/dev/null"]
    restart: unless-stopped